author: Beau Barker
description: A programming blog.
future: true # Include posts with a date in the future
include:
  - ads.txt
locale: en_AU
plugins:
    - jekyll-redirect-from
    - jekyll-seo-tag
    - jekyll-sitemap
    - jekyll-last-modified-at
title: Composed
tagline: A programming blog
url: "https://composed.blog" # the base hostname & protocol for your site
